version: '3.8'
services:
  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "${DB_PORT}:${DB_PORT}"
  scraper:
    build: ./sreality_scraper
    command: scrapy crawl sreality
    volumes:
      - ./sreality_scraper:/app
    depends_on:
      - db
    env_file:
      - .env
  web:
    build: ./server
    command: python3 server.py
    volumes:
      - ./server:/app
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    depends_on:
      - scraper
      - db
    env_file:
      - .env
